###
GET http://localhost:3002/credit-cards


###
POST http://localhost:3002/credit-cards
Content-Type: application/json

{
    "name": "Sergio Ribeiro",
    "number": "1234567890123456"
}

###
GET http://localhost:3002/credit-cards/1234567890123456/invoices

###
GET http://localhost:3002/credit-cards/6543210987654321/invoices

###
GET http://localhost:3002/credit-cards/invoices
