version: '3'

services:
  invoices-api:
    build: .
    entrypoint: dockerize -wait tcp://db:5432 -timeout 40s ./.docker/entrypoint.sh
    container_name: invoices-api
    ports:
      - 3002:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: invoices-api-db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
    #   - ./.docker/postgres:/docker-entrypoint-initdb.d
    #ports:
    #  - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=invoice

  pgadmin:
    image: dpage/pgadmin4
    container_name: invoices-api-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 9002:80
    depends_on:
      - db
